name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --target builder -t ing2isimm2024/sysnetadmin:builder  . ; docker build --cache-from=ing2isimm2024/sysnetadmin:builder -t ing2isimm2024/sysnetadmin:prod  .



      
